language: generic

os:
  - linux
# https://github.com/travis-ci/cpython-builder/pull/3 should be resolved for Mac support

sudo: false
dist: trusty

addons:
  apt:
    packages:
      - texinfo

branches:
  only:
    - master
    - /^test-.*$/

env:
  global:
    - NDK_VER=r16b
    - PYBUILD_SRC=$HOME/pybuild-src
      # $BINTRAY_API_KEY
    - secure: "H6sTN+6bPeQSgO/hhBF/SPPS1Yys8c/gNNBJBCxBMs8kqYfMLIfxtt8bmZtAcIR/9fH3BglGOecuH0Q7ili7K1xf7imW7s4T52jvjxtfWfXs384/Dr4DFH/iGn/jaebkwxz/inb6cAMk6Qn1ODxhbGwzLfe9YM8osNdST3unysXF3kQkIp/c0JXcLAUQhqQPeF9SuWJi7hrWi2fxiAZVFHPH8WszRDylFG/7YgqacPiEtvBkhaB7YNTw2nm6nXKlYAwAKca99Pndm2yPo/9gsIcc2NRvRJFzqnTEfw33w7SO8+NlZXq8fxbtae1YbnBfRyax0jZ/DunJne8T7Zsqh4z9YXBYfORO6+67AZb5XvlSuPpZLV7lHQ/Yz5NKHjl19gu+ZQWDDHQg2K9PepFvaCgTTiHFaWjZ1/9cLvyaQkR6YRJmK/l0fNffEcT9BowfL1b8/VkJ8/4NC7VE1UpI8ETVGsJwucrbkIfsx599zjfk/mM2RbyxGBWPG2u4QaU4hUkekDRb7Hh0xs2jY1SjZKsqzRHF7pPIaKkJ/dmCPrWzPzaxdHIYHxNjBXLehDdtRJsc782995TWX28vCoknED7qwTGo4UkZXe5p3mFnBV8UJsHwAgyRSJ/EFp448pkCEGm84F2uNmUGt1JW4I6Tcjg6a0Tdh9LX2OHuqs/C1x0="

  matrix:
    - ANDROID_PLATFORM=arm
    - ANDROID_PLATFORM=arm64
    - ANDROID_PLATFORM=x86
    - ANDROID_PLATFORM=x86_64

install:
  - pyenv install 3.7-dev && pyenv global 3.7-dev
  - pip install requests
  - |
      pushd $HOME
      HOST_OS="$(uname | tr 'A-Z' 'a-z')"
      wget --no-verbose https://dl.google.com/android/repository/android-ndk-$NDK_VER-$HOST_OS-x86_64.zip
      unzip -q android-ndk-$NDK_VER-$HOST_OS-x86_64.zip
      popd
  - export ANDROID_NDK=$HOME/android-ndk-$NDK_VER

script:
  - python -m pybuild.clean
  - make
  - make test
