name: Converted Workflow
on: workflow_dispatch

env:
  NDK_VER: r16b
  PYBUILD_SRC: /pybuild-src

jobs:
  Build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-18.04
        python:
          - 3.7
        arch:
          # - arm
          - arm64
          # - x86
          # - x86_64
    steps:
      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |-
          sudo apt-get update
          sudo apt-get install -y texinfo
      - uses: actions/checkout@v2
      - name: Install python version
        uses: gabrielfalcao/pyenv-action@v9
        with:
          default: '${{ matrix.python }}'
          command: pip install -U pip  # upgrade pip after installing python

      - run: pyenv install 3.7-dev && pyenv global 3.7-dev
      - run: pip install requests
      - run: >
          pushd $HOME

          HOST_OS="$(uname | tr 'A-Z' 'a-z')"

          wget --no-verbose
          https://dl.google.com/android/repository/android-ndk-$NDK_VER-$HOST_OS-x86_64.zip

          unzip -q android-ndk-$NDK_VER-$HOST_OS-x86_64.zip

          popd
      - run: echo "ANDROID_NDK=$HOME/android-ndk-$NDK_VER" >> $GITHUB_ENV
      - run: echo "TARGET_ARCH_ANDROID=${{ matrix.arch }}" >> $GITHUB_ENV
      - run: echo "TARGET_ARCH_NAME=${{ matrix.arch }}" >> $GITHUB_ENV
      - run: python -m pybuild.clean
      - run: make
      - run: make test