name: Converted Workflow
on: workflow_dispatch

jobs:
  Build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-18.04
        python:
          - 3.7
    steps:
      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |-
          sudo apt-get update
          sudo apt-get install -y texinfo
      - uses: actions/checkout@v2
      - name: Install python version
        uses: gabrielfalcao/pyenv-action@v9
        with:
          default: "${{ matrix.python }}"
          command: pip install -U pip  # upgrade pip after installing python

      - name: Install dependencies
        run: pip install -r requirements.txt

      - run: pyenv install 3.7-dev && pyenv global 3.7-dev
      - run: pip install requests
      - run: >
          pushd $HOME

          HOST_OS="$(uname | tr 'A-Z' 'a-z')"

          wget --no-verbose
          https://dl.google.com/android/repository/android-ndk-$NDK_VER-$HOST_OS-x86_64.zip

          unzip -q android-ndk-$NDK_VER-$HOST_OS-x86_64.zip

          popd
      - run: export ANDROID_NDK=$HOME/android-ndk-$NDK_VER
      - run: python -m pybuild.clean
      - run: make
      - run: make test
        env:
          NDK_VER: r16b
          PYBUILD_SRC: $HOME/pybuild-src